config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'restaurants/show', to: 'restaurants#show'
  get 'restaurants/index', to: 'restaurants#index'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :reviews, only: [:create, :destroy]

end

app/views/pages/_thumbnails.html.erb
<div class="col-sm-6 col-md-4">
	<div class="thumbnail">
	 <%= image_tag("orazio_thumb.jpg", size: "300x300", class: "thumbimages") %>
	  <div class="caption">
	    <h3>Da Orazio</h3>
	    <p>Chef and partner Orazio D'Elia, formerly of Popolo and Icebergs, puts a serious focus on Neapolitan-style wood-fired pizza and Roman-style porchetta.</p>
	    <p><%= link_to "More", restaurants_show_path(:id => "da-orazio-pizza-porchetta-bondi-beach"), class: "btn btn-primary thumbnail-buttons" %></p>
	  </div>
	</div>
</div>
<div class="col-sm-6 col-md-4">
	<div class="thumbnail">
	 <%= image_tag("pavillion_thumb.jpg", size: "250x200", class: "thumbimages") %>
	  <div class="caption">
	    <h3>Coogee Pavillion</h3>
	    <p>For casual bites, snag a stool by the bar and feast on some of the city's best Neapolitan-style pizza,
			bubbly and gently charred from the wood-fired oven.</p>
	    <p><%= link_to "More", restaurants_show_path(:id => "coogee-pavilion-coogee"),
												class: "btn btn-primary thumbnail-buttons" %></p>
	  </div>
	</div>
</div>
<div class="col-sm-6 col-md-4">
	<div class="thumbnail">
	 <%= image_tag("lucio_thumb.jpg", size: "300x300", class: "thumbimages") %>
	  <div class="caption">
	    <h3>Lucio Pizzeria</h3>
	    <p>Despite a lack of signage, Lucio’s reputation is such that tables fill from the moment it opens.</p>
	    <p><%= link_to "More", restaurants_show_path(:id => "lucio-pizzeria-darlinghurst"),
								class: "btn btn-primary thumbnail-buttons" %></p>
	  </div>
	</div>
</div>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<!--JUMBOTRON-->
<div class="background">
<div class="jumbotron">
  <div class="container">
    <h2 id="jumbo-caption">Find Your Pizza</h2>
		    <div class="search-div">
				<span class="glyphicon glyphicon-search jumbo-search-icon" aria-hidden="true"></span>
			  <%= form_tag(restaurants_index_path, :method => "get", id: "search-form", 
			  										class: "input-group search-container") do %>
			  <%= text_field_tag :search, params[:search], placeholder: "Suburb", class: "form-control search-bar" %>
			  <%= select_tag(:state, options_for_select(['NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'NT', 'ACT']), 
			  												{:class => "state-select"}) %>
				<% end %> 
		    </div>
	</div>
</div>
<!--THUMBNAILS-->
<div class="container">
	<span id="latest-news">Latest News</span>
	<p id="news-caption">Explore the latest news from Sydney's best pizzeria's</p>
	<hr>
	<div class="row">
	  <%= render 'pages/thumbnails' %>
	</div>
</div>
</div>