config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'restaurants/show', to: 'restaurants#show'
  get 'restaurants/index', to: 'restaurants#index'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :reviews, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="container-fluid footer">
		<a href="/" id="logo"><font color="white">Pizza</font><font color="black">Me</font></a>
	<div>
	<div class="yelp-footer">
		<span class="yelp-span">Restaurant information courtesy of Yelp.</span>
		<%= link_to (image_tag("yelp_burst_white.png", class: "yelp-burst")), "https://www.yelp.com" %>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar .navbar-expand{-sm|-md|-lg|-xl}">
	<!--PIZZAME LOGO-->
    <div class="navbar-logo-div">
	  <%= link_to "PizzaMe", root_path, class: "navbar-brand"%>
    </div>
	<!--SEARCH BAR-->
	<div class="navbar-search-div hidden-xs">
		<span class="glyphicon glyphicon-search nav-search-icon" aria-hidden="true"></span>
	  <%= form_tag(restaurants_index_path, :method => "get", id: "search-form",
	  										class: "form-inline nav-form") do %>
	  <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control navbar-search" %>
	  <%= select_tag(:state, options_for_select(['NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'NT', 'ACT']),
	  												{:class => "nav-state-select"}) %>
		<% end %>
	</div>
	<!--NAVIGATION LINKS-->

	<ul class="navbar-user-links navbar-right">
		<% if logged_in? %>
		<li class="login-nav hidden-xs"><%= current_user.name %></li>
		<li><div class="avadiv"><%=link_to image_tag(current_user.profile_image, size: "40x40", class: "avatar"), 									current_user %></div></li>
		<% else%>
		<li><%= link_to "Log-in/Sign-up", login_path, class: "login-nav hidden-xs" %></li>
		<li class="social-parent">
			<%= link_to "", "/auth/google_oauth2", class: "fa fa-google-plus-square fa-3x social-icons hidden-xs" %>
		</li>
		<li class="social-parent">
			<%= link_to "", "/auth/facebook", class: "fa fa-facebook-square fa-3x social-icons hidden-xs" %>
		</li>
		<% end %>
		<!--DROPDOWN MENU-->
		<li><button type="button" class="btn btn-default dropdown-toggle menu-button" data-toggle="dropdown" 						aria-haspopup="true" aria-expanded="false">
  		  <span class="fa fa-align-justify fa-3x"></span></button>
	          <ul class="dropdown-menu dropdown-menu-right">
	            <li><a href="/">Pizza</a></li>
							<% if logged_in? %>
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<% if current_user.admin? %>
									<li><%= link_to "All users", users_path %></li>
								<% end %>
								<li role="separator" class="divider"></li>
								<li><a href="/logout" data-method="delete">Log out</a></li>
							<% else %>
							<li role="separator" class="divider"></li>
				            <li><%= link_to "Login", login_path %></li>
							<li><%= link_to "Signup", signup_path %></li>
							<% end %>
	          </ul>
		</li>
	</ul>
  </nav>
  <div class="container-fluid sub-nav">
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | PizzaMe</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	
  </head>

  <body>
	<%= render 'layouts/header' %>
	<% flash.each do |message_type, message| %>
	        <div class="alert alert-<%= message_type %>"><%= message %></div>
	<% end %>
    <%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
	
  </body>
</html>